# Generated by Django 4.1.7 on 2023-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=255, verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость услуги')),
                ('service_status', models.BooleanField(default=True, verbose_name='Услуга доступна')),
            ],
        ),
    ]
