# Generated by Django 4.1.7 on 2023-03-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('record_time', models.DateTimeField(verbose_name='Время записи')),
                ('visitors_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('visitors_email', models.EmailField(max_length=50, verbose_name='Email клиента')),
                ('visitors_phone', models.CharField(max_length=18, verbose_name='Номер телефона клиента')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Услуга')),
            ],
        ),
    ]
