# Generated by Django 4.1.7 on 2023-03-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_status',
            field=models.BooleanField(default=True, verbose_name='Услуга доступна'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('record_time', models.DateTimeField(verbose_name='Время записи')),
                ('visitors_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('visitors_email', models.EmailField(max_length=50, verbose_name='Email клиента')),
                ('visitors_phone', models.CharField(max_length=18, verbose_name='Номер телефона клиента')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.services', verbose_name='Услуга')),
            ],
        ),
    ]
